export const FAQsArray = [
    {
      question: "What is a marketing website?",
      answer: "A marketing website is a website that is designed to promote a business or organization. It is often used to provide information about a company, its products or services, and to provide contact information for potential customers.",
    },
    {
      question: "What is a web application?",
      answer: "A web application is a website that provides a set of features to its users. Unlike marketing websites that are often accessible publicly, web applications usually restrict access to their features via a login, and provide a dashboard for their users to manage their profile, preferences or billing information.",
    },
    {
      question: "Build a project in blocks...what does that mean?",
      answer: "Viva web design builds custom websites tailored to your needs. We think of your website as a modular interface built by gluing together several reusable blocks. These blocks could consist of anything; a hero section, for example, or a list of testimonials, a list of blog articles, or an interactive map. Basically, anything you could imagine on a website could be a block. As part of our web development services, we code the user interface and logic of these blocks from scratch, and make them available for you on the headless CMS. This means you can build as many pages as you want by dragging and dropping blocks and filling them with content.",
    },
    {
      question: "Why do I need a custom website?",
      answer: "Because a custom website is not generated by a no-code tool, you can have any feature that is buildable on the browser without rebuilding the entire website. When you use a no-code tool, you're bound to the features and plugins that the tool provides. This is why most websites look the same. They all use the same plugins and features. The advantage of starting with a custom website is the total absence of any limits. Any API integration you have in mind is by default possible. Moreover, it opens the opportunity to have complex interactive elements on your website since you have full control over the code. Because custom websites are completely flexible, it makes them more durable, regardless of any feature or integration you decide to add at any point in the future.",
    },

    // More questions...
  ]